services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  LiquidLight\ElevateToAdmin\:
    resource: '../Classes/*'

  LiquidLight\ElevateToAdmin\EventListener\BeforeUserLogoutEventListener:
    tags:
      - name: event.listener
        identifier: 'elevate-to-admin/before-user-logout'
        event: TYPO3\CMS\Core\Authentication\Event\BeforeUserLogoutEvent
