name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  PHP_VERSION: '8.2'
  COMPOSER_INSTALL_FLAGS: '--no-interaction --no-scripts --no-progress --optimize-autoloader --ansi --ignore-platform-reqs'

jobs:
  lint:
    name: ${{ matrix.name }}
    runs-on: ubuntu-latest
    container:
      image: typo3/core-testing-php82
    strategy:
      matrix:
        include:
          - name: "PHP CS Fixer"
            command: "composer php-cs-fixer:dry-run"
          - name: "PHP Parallel Lint"
            command: "composer parallel-lint"
          - name: "Composer Normalize"
            command: "composer composer-normalize:dry-run"
          - name: "EditorConfig"
            command: "composer editorconfig:dry-run"
          - name: "YAML Lint"
            command: "composer yaml-lint"
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 10

      - name: Cache Build dependencies
        uses: actions/cache@v4
        with:
          path: .Build
          key: build-${{ hashFiles('composer.json', 'composer.lock') }}
          restore-keys: |
            build-

      - name: Install Composer dependencies
        run: composer install ${{ env.COMPOSER_INSTALL_FLAGS }}

      - name: Run ${{ matrix.name }}
        run: ${{ matrix.command }}

  test:
    name: Unit Tests (PHP ${{ matrix.php-version }})
    runs-on: ubuntu-latest
    container:
      image: typo3/core-testing-php${{ matrix.php-version }}
    strategy:
      matrix:
        php-version: ['82', '83']
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 10

      - name: Cache Build dependencies
        uses: actions/cache@v4
        with:
          path: .Build
          key: build-php${{ matrix.php-version }}-${{ hashFiles('composer.json', 'composer.lock') }}
          restore-keys: |
            build-php${{ matrix.php-version }}-
            build-

      - name: Install Composer dependencies
        run: composer install ${{ env.COMPOSER_INSTALL_FLAGS }}

      - name: Run Unit Tests
        run: composer test-unit
